name: kronk
description: "My Kronk project. now it is in development mode. it will be finished before december 2024."
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ^3.5.3
  
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons:
  equatable:
  path_provider:
  hive:
  flutter_bloc:
  rive:
  lottie:
  iconsax:
  page_transition:
  dio:
  flutter_staggered_grid_view:
  icons_plus:
  provider:
  flutter_svg:
  connectivity_plus:
  cached_network_image:
  custom_refresh_indicator:
  image_picker:
  permission_handler:
  crop_your_image:
  flutter_image_compress:
  google_fonts:
  image:
  url_launcher:
  jwt_decoder:
  flutter_launcher_icons:
  web_socket_channel:
  google_sign_in:
  firebase_core:
  firebase_auth:
  flutter_cache_manager:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/ui-icons/
    - assets/animations/


flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/app_icons/kronk-app-icon.png"
  image_path_ios: "assets/app_icons/kronk-app-icon.png"
  adaptive_icon_foreground: "assets/app_icons/kronk-foreground.png"
  adaptive_icon_background: "assets/app_icons/kronk-background.png"
  adaptive_icon_monochrome: "assets/app_icons/kronk-foreground-monochrome.png"
  min_sdk_android: 21
  remove_alpha_ios: true
