// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtDDsn8aY7dQQbxSNlRHh3mf7c6B_eZYA',
    appId: '1:1000875999791:android:64ebf5f7bdbe008be17cda',
    messagingSenderId: '1000875999791',
    projectId: 'my-development-project-1-cdd58',
    storageBucket: 'my-development-project-1-cdd58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnW2SS8wNqV3tVpKnmsVElPXRT3juQuX0',
    appId: '1:1000875999791:ios:4465d0cf79f9bd7ce17cda',
    messagingSenderId: '1000875999791',
    projectId: 'my-development-project-1-cdd58',
    storageBucket: 'my-development-project-1-cdd58.appspot.com',
    androidClientId: '1000875999791-i7r5dnrltirkorj15pojajfcve96boif.apps.googleusercontent.com',
    iosClientId: '1000875999791-qodfl3jef844mblvr80d2cmc181nmu3b.apps.googleusercontent.com',
    iosBundleId: 'com.kronk.kronk',
  );

}